/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuas.View;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author AdityaHKP
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MainFrame() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        scrollPane.setViewportView(new PanelDaftar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        labelPageTitle = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuMenu = new javax.swing.JMenu();
        menubuttonDaftar = new javax.swing.JMenuItem();
        menubuttonMasuk = new javax.swing.JMenuItem();
        menubuttonKeluar = new javax.swing.JMenuItem();
        menubuttonRiwayat = new javax.swing.JMenuItem();
        menubuttonLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.control);

        scrollPane.setBackground(java.awt.SystemColor.controlLtHighlight);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoAppSmall.png"))); // NOI18N

        labelPageTitle.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        labelPageTitle.setText("Daftar Logistik");

        menuMenu.setText("Menu");

        menubuttonDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuiconBoxS.png"))); // NOI18N
        menubuttonDaftar.setText("Daftar Logistik");
        menubuttonDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonDaftarActionPerformed(evt);
            }
        });
        menuMenu.add(menubuttonDaftar);

        menubuttonMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuiconInS.png"))); // NOI18N
        menubuttonMasuk.setText("Logistik Masuk");
        menubuttonMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonMasukActionPerformed(evt);
            }
        });
        menuMenu.add(menubuttonMasuk);

        menubuttonKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuiconOutS.png"))); // NOI18N
        menubuttonKeluar.setText("Logistik Keluar");
        menubuttonKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonKeluarActionPerformed(evt);
            }
        });
        menuMenu.add(menubuttonKeluar);

        menubuttonRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuiconHistoryS.png"))); // NOI18N
        menubuttonRiwayat.setText("Riwayat");
        menubuttonRiwayat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonRiwayatActionPerformed(evt);
            }
        });
        menuMenu.add(menubuttonRiwayat);

        menubuttonLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menuiconLogoutS.png"))); // NOI18N
        menubuttonLogout.setText("Log Out");
        menubuttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubuttonLogoutActionPerformed(evt);
            }
        });
        menuMenu.add(menubuttonLogout);

        menuBar.add(menuMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(labelPageTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 481, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPageTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menubuttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonLogoutActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Apakah anda yakin ingin log out?",
                "Konfirmasi Log Out",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            this.dispose();
            new LoginFrame().setVisible(true);
        }
    }//GEN-LAST:event_menubuttonLogoutActionPerformed

    private void menubuttonDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonDaftarActionPerformed
        setScrollView(new PanelDaftar(), "Daftar Logistik");
    }//GEN-LAST:event_menubuttonDaftarActionPerformed

    private void menubuttonRiwayatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonRiwayatActionPerformed
        setScrollView(new PanelRiwayat(), "Riwayat");
    }//GEN-LAST:event_menubuttonRiwayatActionPerformed

    private void menubuttonMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonMasukActionPerformed
        setScrollView(new PanelDaftar(), "Daftar Logistik");
        MasukFrame masukFrame = new MasukFrame();
        setDataCrudView(masukFrame);
    }//GEN-LAST:event_menubuttonMasukActionPerformed

    private void menubuttonKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubuttonKeluarActionPerformed
        setScrollView(new PanelDaftar(), "Daftar Logistik");
        KeluarFrame keluarFrame = new KeluarFrame();
        setDataCrudView(keluarFrame);
    }//GEN-LAST:event_menubuttonKeluarActionPerformed

    void setScrollView(JPanel panel, String pageTitle) {
        scrollPane.setViewportView(panel);
        labelPageTitle.setText(pageTitle);
    }
    
    void setDataCrudView(JFrame frame) {
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelPageTitle;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuMenu;
    private javax.swing.JMenuItem menubuttonDaftar;
    private javax.swing.JMenuItem menubuttonKeluar;
    private javax.swing.JMenuItem menubuttonLogout;
    private javax.swing.JMenuItem menubuttonMasuk;
    private javax.swing.JMenuItem menubuttonRiwayat;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
