/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projectuas.View;

import java.io.File;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import projectuas.Controller.ControllerLogistik;
import projectuas.Model.Logistik;
import java.util.List;
import projectuas.Controller.ExportCSV;
import projectuas.Controller.ExportPDF;
import projectuas.Model.Riwayat;

/**
 *
 * @author AdityaHKP
 */
public class PanelDaftar extends javax.swing.JPanel {

    /**
     * Creates new form panelDaftar
     */
    private ControllerLogistik controllerLogistik;
    
    public PanelDaftar() {
        initComponents();
        controllerLogistik = new ControllerLogistik();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        buttonSaveCsv = new javax.swing.JButton();
        buttonSavePdf = new javax.swing.JButton();
        buttonKurang = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonHapus = new javax.swing.JButton();
        labelSimpan = new javax.swing.JLabel();
        buttonRefresh = new javax.swing.JButton();
        scrollPaneDaftar = new javax.swing.JScrollPane();
        tableLogistik = new javax.swing.JTable();

        setBackground(java.awt.SystemColor.control);

        jPanel1.setBackground(java.awt.SystemColor.control);

        buttonSaveCsv.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        buttonSaveCsv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCsv.png"))); // NOI18N
        buttonSaveCsv.setText("CSV");
        buttonSaveCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveCsvActionPerformed(evt);
            }
        });

        buttonSavePdf.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        buttonSavePdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPdf.png"))); // NOI18N
        buttonSavePdf.setText("PDF");
        buttonSavePdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSavePdfActionPerformed(evt);
            }
        });

        buttonKurang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMinus.png"))); // NOI18N
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });

        buttonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPlus.png"))); // NOI18N
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonHapus.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        buttonHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTrash.png"))); // NOI18N
        buttonHapus.setText("Hapus Data");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        labelSimpan.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        labelSimpan.setText("Simpan");

        buttonRefresh.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        buttonRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        buttonRefresh.setText("Muat Ulang");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSavePdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSaveCsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelSimpan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buttonRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKurang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonSaveCsv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSavePdf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tableLogistik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollPaneDaftar.setViewportView(tableLogistik);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPaneDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        MasukFrame masukFrame = new MasukFrame();
        setDataCrudView(masukFrame);
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
        KeluarFrame keluarFrame = new KeluarFrame();
        setDataCrudView(keluarFrame);
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus semua data logistik?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if (selectedOption == JOptionPane.YES_OPTION) {
            boolean berhasil = controllerLogistik.deleteLogistik();

            if (berhasil) {
                JOptionPane.showMessageDialog(this, "Berhasil menghapus semua data logistik.");
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data logistik.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        controllerLogistik.hapusKosong();
        refreshTable();
        JOptionPane.showMessageDialog(this, "Berhasil memuat ulang data logistik.");
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonSaveCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveCsvActionPerformed
        int returnVal = fileChooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String exportPath = file.getAbsolutePath();

            if (!exportPath.toLowerCase().endsWith(".csv")) {
                exportPath += ".csv";
            }

            List<Logistik> logistikToWrite = controllerLogistik.getAllLogistik();

            try {
                ExportCSV exporter = new ExportCSV();
                exporter.exportCSVLogistik(exportPath, logistikToWrite);
                JOptionPane.showMessageDialog(this, "CSV berhasil disimpan di: " + exportPath);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan CSV: " + e.getMessage());
            }
        } else {
            System.out.println("Batal menyimpan.");
        }
    }//GEN-LAST:event_buttonSaveCsvActionPerformed

    private void buttonSavePdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSavePdfActionPerformed
        int returnVal = fileChooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            String exportPath = file.getAbsolutePath();
            if (!exportPath.toLowerCase().endsWith(".pdf")) {
                exportPath += ".pdf";
            }

            List<Logistik> logistikToWrite = controllerLogistik.getAllLogistik();

            try {
                ExportPDF.exportPDFLogistik(exportPath, logistikToWrite);
                JOptionPane.showMessageDialog(this, "PDF berhasil disimpan di: " + exportPath);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan PDF: " + e.getMessage());
            }
        } else {
            System.out.println("Batal menyimpan.");
        }
    }//GEN-LAST:event_buttonSavePdfActionPerformed
    
    void setDataCrudView(JFrame frame) {
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }
    
        private void refreshTable() {
        List<Logistik> logistikList = controllerLogistik.getAllLogistik();
        DefaultTableModel tableModel = (DefaultTableModel) tableLogistik.getModel();
        tableModel.setRowCount(0); // Clear existing data

        for (Logistik logistik : logistikList) {
            tableModel.addRow(new Object[]{logistik.getNama(), logistik.getJumlah()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonKurang;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSaveCsv;
    private javax.swing.JButton buttonSavePdf;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelSimpan;
    private javax.swing.JScrollPane scrollPaneDaftar;
    private javax.swing.JTable tableLogistik;
    // End of variables declaration//GEN-END:variables
}
